use num_enum::{UnsafeFromPrimitive};
use strum::IntoEnumIterator;
use strum_macros::EnumIter;

pub enum InstructionResult {
    Continue,
    Return,
    Exception
}

#[derive(UnsafeFromPrimitive, EnumIter, Debug, Copy, Clone, PartialEq)]
#[repr(u8)]
#[allow(non_camel_case_types)]
pub enum Instruction {
    nop = 0,
    aconst_null = 1,
    iconst_m1 = 2,
    iconst_0 = 3,
    iconst_1 = 4,
    iconst_2 = 5,
    iconst_3 = 6,
    iconst_4 = 7,
    iconst_5 = 8,
    lconst_0 = 9,
    lconst_1 = 10,
    fconst_0 = 11,
    fconst_1 = 12,
    fconst_2 = 13,
    dconst_0 = 14,
    dconst_1 = 15,
    bipush = 16,
    sipush = 17,
    ldc = 18,
    ldc_w = 19,
    ldc2_w = 20,
    iload = 21,
    lload = 22,
    fload = 23,
    dload = 24,
    aload = 25,
    iload_0 = 26,
    iload_1 = 27,
    iload_2 = 28,
    iload_3 = 29,
    lload_0 = 30,
    lload_1 = 31,
    lload_2 = 32,
    lload_3 = 33,
    fload_0 = 34,
    fload_1 = 35,
    fload_2 = 36,
    fload_3 = 37,
    dload_0 = 38,
    dload_1 = 39,
    dload_2 = 40,
    dload_3 = 41,
    aload_0 = 42,
    aload_1 = 43,
    aload_2 = 44,
    aload_3 = 45,
    iaload = 46,
    aaload = 50,
    istore = 54,
    lstore = 55,
    dstore = 57,
    astore = 58,
    istore_0 = 59,
    istore_1 = 60,
    istore_2 = 61,
    istore_3 = 62,
    lstore_0 = 63,
    lstore_1 = 64,
    lstore_2 = 65,
    lstore_3 = 66,
    dstore_0 = 71,
    dstore_1 = 72,
    dstore_2 = 73,
    dstore_3 = 74,
    astore_0 = 75,
    astore_1 = 76,
    astore_2 = 77,
    astore_3 = 78,
    iastore = 79,
    aastore = 83,
    pop = 87,
    dup = 89,
    iadd = 96,
    ladd = 97,
    dadd = 99,
    isub = 100,
    dsub = 103,
    imul = 104,
    lmul = 105,
    dmul = 107,
    idiv = 108,
    ldiv = 109,
    ddiv = 111,
    lrem = 113,
    dneg = 119,
    ishl = 120,
    ixor = 130,
    iinc = 132,
    i2l = 133,
    l2i = 136,
    l2d = 138,
    f2d = 141,
    i2b = 145,
    i2c = 146,
    lcmp = 148,
    ifeq = 153,
    ifne = 154,
    iflt = 155,
    ifge = 156,
    ifgt = 157,
    ifle = 158,
    if_icmpeq = 159,
    if_icmpge = 162,
    if_icmpgt = 163,
    if_acmpeq = 165,
    if_acmpne = 166,
    goto = 167,
    ireturn = 172,
    lreturn = 173,
    dreturn = 175,
    areturn = 176,
    _return = 177,
    getstatic = 178,
    putstatic = 179,
    getfield = 180,
    putfield = 181,
    invokevirtual = 182,
    invokespecial = 183,
    invokestatic = 184,
    invokeinterface = 185,
    new = 187,
    newarray = 188,
    anewarray = 189,
    arraylength = 190,
    athrow = 191,
    checkcast = 192,
    instanceof = 193,
    breakpoint = 202,
    impdep1 = 254,
    impdep2 = 255,
}

impl Instruction {
    pub fn exists(code: u8) -> bool {
        for i in Instruction::iter() {
            if i as u8 == code {
                return true;
            }
        }

        false
    }
}

#[inline(always)]
pub const fn instruction_length(instr: Instruction) -> usize {
    use Instruction::*;

    match instr {
        nop => 1,
        aconst_null => 1,
        iconst_m1 => 1,
        iconst_0 => 1,
        iconst_1 => 1,
        iconst_2 => 1,
        iconst_3 => 1,
        iconst_4 => 1,
        iconst_5 => 1,
        lconst_0 => 1,
        lconst_1 => 1,
        fconst_0 | fconst_1 | fconst_2 => 1,
        dconst_0 | dconst_1 => 1,
        bipush => 2,
        sipush => 3,
        ldc => 2,
        ldc_w => 3,
        ldc2_w => 3,
        iload => 2,
        lload => 2,
        fload => 2,
        dload => 2,
        aload => 2,
        iload_0 => 1,
        iload_1 => 1,
        iload_2 => 1,
        iload_3 => 1,
        lload_0 => 1,
        lload_1 => 1,
        lload_2 => 1,
        lload_3 => 1,
        fload_0 | fload_1 | fload_2 | fload_3 => 1,
        dload_0 | dload_1 | dload_2 | dload_3 => 1,
        aload_0 | aload_1 | aload_2 | aload_3 => 1,
        iaload => 1,
        aaload => 1,
        istore => 2,
        lstore => 2,
        dstore => 2,
        astore => 2,
        istore_0 => 1,
        istore_1 => 1,
        istore_2 => 1,
        istore_3 => 1,
        lstore_0 => 1,
        lstore_1 => 1,
        lstore_2 => 1,
        lstore_3 => 1,
        dstore_0 | dstore_1 | dstore_2 | dstore_3 => 1,
        astore_0 | astore_1 | astore_2 | astore_3 => 1,
        iastore => 1,
        aastore => 1,
        pop => 1,
        dup => 1,
        iadd => 1,
        ladd => 1,
        dadd => 1,
        isub => 1,
        dsub => 1,
        imul => 1,
        lmul => 1,
        dmul => 1,
        idiv => 1,
        ldiv => 1,
        ddiv => 1,
        lrem => 1,
        dneg => 1,
        ishl => 1,
        ixor => 1,
        iinc => 3,
        i2l => 1,
        l2i => 1,
        l2d => 1,
        f2d => 1,
        i2b => 1,
        i2c => 1,
        lcmp => 1,
        ifeq | ifne | iflt | ifge | ifgt | ifle | if_icmpeq | if_icmpge | if_icmpgt => 3,
        if_acmpeq | if_acmpne => 3,
        goto => 3,
        ireturn => 1,
        lreturn => 1,
        dreturn => 1,
        areturn => 1,
        _return => 1,
        getstatic => 3,
        putstatic => 3,
        getfield => 3,
        putfield => 3,
        invokevirtual => 3,
        invokespecial => 3,
        invokestatic => 3,
        invokeinterface => 5,
        new => 3,
        newarray => 2,
        anewarray => 3,
        arraylength => 1,
        athrow => 1,
        checkcast => 3,
        instanceof => 3,
        breakpoint => 1,
        impdep1 => 1,
        impdep2 => 1
    }
}